---
- hosts: webserver,appserver
  become: yes
  tasks:
          - name: installing package
            yum: name={{item}} state=absent
            with_items:
                    - git
                    - tree

