---
- hosts: webserver
  become: yes
  vars:
    - x: httpd
    - y: present
    - z: started 
  tasks:
    - name: installing httpd package
      yum:      
        name: "{{x}}"
        state: "{{y}}" 
    - name: service httpd start
      service: 
        name: "{{x}}"
        state: "{{z}}"     
